spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        hibernate.hbm2ddl.import_files: import.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:E:\test;MODE=MYSQL
    username: sa
    password:
security.oauth2.resource.filter-order: 3

security.signing-key: MaYzkSjmkzPC57L
security.encoding-strength: 53
security.security-realm: Spring Boot JWT Example Realm

security.jwt.client-id: testjwtclientid
security.jwt.client-secret: XY7kmzoNzl100
security.jwt.grant-type: password
security.jwt.scope-read: read
security.jwt.scope-write: write
security.jwt.resource-ids: testjwtresourceid

cross.origin: http://localhost:4200

cloudinary:
  environment.variable: cloudinary://472951833181896:PNFHnk-FdjEfHgxR4Eu5ce39p7U@bravewall/

spring.mail:
  from: University Admission System
  debug: false
  host: smtp.gmail.com
  port: 587
  username: facultiesgit@gmail.com
  password: z200198l192ws
  transport.protocol: smtp
  properties.mail.smtp:
    auth: true
    starttls.enable: true
server:
  address: 192.168.100.7
